services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  notification_service:
    image: notification_service
    depends_on:
      - broker
    environment:
      - KAFKA_BROKER=broker:29092
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}

  payu_service:
    image: payu_service
    depends_on:
      - broker
    environment:
      - KAFKA_BROKER=broker:29092
      - PAYU_POS_ID=${PAYU_POS_ID}
      - PAYU_CLIENT_ID=${PAYU_CLIENT_ID}
      - PAYU_SECRET=${PAYU_SECRET}
      - PAYU_NOTIFY_URL=${PAYU_NOTIFY_URL}
      - PAYU_CONTINUE_URL=${PAYU_CONTINUE_URL}

  membership_service:
    image: membership_service
    ports:
      - 8001:8001
    depends_on:
      - broker
    environment:
      - KAFKA_BROKER=broker:29092

  tpay_payment_service:
    image: tpay_payment_service
    ports:
      - 8002:8002
    depends_on:
      - broker
    environment:
      - KAFKA_BROKER=broker:29092
