services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"

  kong-migrations:
    image: kong:3.6
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: kong

  kong:
    image: kong:3.6
    container_name: kong
    depends_on:
      - kong-database
      - kong-migrations
    environment:
      KONG_DATABASE: off
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:28001, 0.0.0.0:8444 ssl
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
    ports:
      - "8000:8000"   # proxy
      - "8001:8001"   # admin API
      - "8444:8444"   # admin HTTPS
      - "8002:8002"   # proxy HTTPS
    volumes:
      - ./kong/kong.yml:/usr/local/kong/kong.yml

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

  notification_service:
    image: notification_service
    hostname: notification-service
    depends_on:
      - broker
    environment:
      - KAFKA_BROKER=broker:29092
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}

  payu_service:
    image: payu_service
    hostname: payu-service
    ports:
      - 8007:8007
    depends_on:
      - broker
    environment:
      - KAFKA_BROKER=broker:29092
      - PAYU_POS_ID=${PAYU_POS_ID}
      - PAYU_CLIENT_ID=${PAYU_CLIENT_ID}
      - PAYU_SECRET=${PAYU_SECRET}
      - PAYU_NOTIFY_URL=${PAYU_NOTIFY_URL}
      - PAYU_CONTINUE_URL=${PAYU_CONTINUE_URL}

  membership_service:
    image: membership_service
    hostname: membership-service
    ports:
      - 8005:8005
    depends_on:
      - broker
      - redis
    environment:
      - KAFKA_BROKER=broker:29092
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - EXTENSION_INTENT_KEY_PREFIX=${EXTENSION_INTENT_KEY_PREFIX}
      - EXTENSION_INTENT_TTL_SECONDS=${EXTENSION_INTENT_TTL_SECONDS}
      
  tpay_payment_service:
    image: tpay_payment_service
    hostname: tpay-service
    ports:
      - 8006:8006
    depends_on:
      - broker
    environment:
      - KAFKA_BROKER=broker:29092
      - TPAY_CLIENT_ID=${TPAY_CLIENT_ID}
      - TPAY_CLIENT_SECRET=${TPAY_CLIENT_SECRET}
      - TPAY_API_URL=${TPAY_API_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}

  classes_service:
    image: classes_service
    hostname: classes-service
    ports:
      - 8003:8003
    depends_on:
      - broker
    environment:
      - KAFKA_BROKER=broker:29092

  reservation_service:
    image: reservation_service
    hostname: reservation-service
    ports:
      - 8004:8004
    depends_on:
      - broker
    environment:
      - KAFKA_BROKER=broker:29092
