version: "3.8"

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"

  kong-migrations:
    image: kong:3.6
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: kong

  kong:
    image: kong:3.6
    container_name: kong
    depends_on:
      - kong-database
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"   # proxy
      - "8001:8001"   # admin API
      - "8444:8444"   # admin HTTPS
      - "8002:8002"   # proxy HTTPS

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "5000:5000"
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  pass-service:
    build:
      context: ./pass-service
    container_name: pass-service
    ports:
      - "5001:5001"

  membership-service:
    build:
      context: ./membership_service
    container_name: membership_service
    ports:
      - "5002:5002"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

#  classes-service:
#    build: .
#    container_name: classes-service
#    ports:
#      - "5002:5000"
#
#  reservation-service:
#    build: .
#    container_name: reservation-service
#    ports:
#      - "5003:5000"
#
#  payu-service:
#    build: .
#    container_name: payu-service
#    ports:
#      - "5004:5000"
#
#  tpay-service:
#    build: .
#    container_name: tpay-service
#    ports:
#      - "5005:5000"
#
#  notification-service:
#    build: .
#    container_name: notification-service
#    ports:
#      - "5006:5000"